name: Run Daily Arxiv

on:
  workflow_dispatch:
  schedule:
    - cron: "00 12 * * *"
  push:
    branches:
      - main
# env:

#   GITHUB_NAME: zhuwenxing
#   GITHUB_EMAIL: wenxing.zhu@qq.com

permissions:
  contents: write


jobs:
  sync:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxivscraper
          pip install requests

      - name: Run daily arxiv 
        run: |
          python daily_arxiv.py
          
      - name: Push new daily.md
        uses: github-actions-x/commit@v2.9
        with:
#           github-token: ${{ secrets.G_T }}
          commit-message: "update today arxiv"
          files: README.md daily.json
          rebase: 'true'
#           name: ${{ env.GITHUB_NAME }}
#           email: ${{ env.GITHUB_EMAIL }}

      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
